name : mern ci
on:
  push:
    branches: [prod]
jobs:
  mongo-init:
    runs-on: ubuntu-latest
    services :
        image: mongo
        ports: ['27017:27017']
test:
    runs-on: ubuntu-latest 

    steps:
      -name: Checkout Repository
      -uses: actions/checkout@v3
      -uses: actions/checkout@v6
      -name: Setup Node.js
      -uses: actions/setup-node@v3
      with:
        node-version: "18"
      -name: Install Dependencies for backend  

    steps : 
        -name: waiting for mongodb to ready
        uses: actions/checkout@v6
        -name: Setup Node.js
        uses: actions/setup-node@v3
        with:
        node-version: "18"
        run : |
          until nc -z localhost 27017 ; do
          echo "waiting for mongodb..."
          sleep 2
          done 
            echo "mongodb is ready!"
        -name : seed mongodb
        working-directory : ./backend
        run: |
         npm install
         node seedTaskData.js

         
      

